"""
Written by: TheBioinformaticalGardener (Marius Dobbe Klemetsen)
Created:    2025-08-22
Disclaimer:
The ground work for this program was generated by OpenAI ChatGPT with the GPT-5 model (at 2025-08-22). It was however error prone, leading to necessary edits by the author.


This program generates QR codes.
"""

import segno
from PIL import Image, ImageDraw, ImageFont
import io

# Parameters
num_codes = 20
cols = 4  # number of QR codes per row
scale = 5  # scaling factor for QR codes
border = 2  # border around each QR code
font_size = 20

# num_codes = 20
# cols = 5  # number of QR codes per row
# scale = 5  # scaling factor for QR codes
# border = 2  # border around each QR code
# font_size = 20

# Try loading a font
try:
    font = ImageFont.truetype("arial.ttf", font_size)
except OSError:
    font = ImageFont.load_default()

qr_images = []

for i in range(1, num_codes + 1):
    label = f"sample{i}"
    qr = segno.make(label, error="L", version=5)

    # Save QR code into memory as PNG
    buf = io.BytesIO()
    qr.save(
        f"individual_QR_codes/{label}.png",
        kind="png",
        scale=scale,
        border=border,
        light=None,
    )
    qr.save(buf, kind="png", scale=scale, border=border, light=None)
    buf.seek(0)
    img = Image.open(buf)

    # Convert img 1-bit bilevel mode to RGBA:
    img = img.convert("RGBA")

    datas = img.getdata()
    new_data = []
    for item in datas:
        # item is (R,G,B,A)
        if item[0] == 255 and item[1] == 255 and item[2] == 255:
            # turn white into fully transparent
            new_data.append((255, 255, 255, 0))
        else:
            # keep black as opaque
            new_data.append((0, 0, 0, 255))
    img.putdata(new_data)

    # Add space for label below
    w, h = img.size
    labeled_img = Image.new("RGBA", (w, h + font_size + 10), (0, 0, 0, 0))

    # Paste img on transparent background
    labeled_img.paste(img, (0, 0), mask=img)

    # Draw text centered
    draw = ImageDraw.Draw(labeled_img)
    bbox = draw.textbbox((0, 0), label, font=font)
    text_w, text_h = bbox[2] - bbox[0], bbox[3] - bbox[1]

    draw.text(((w - text_w) // 2, h + 5), label, fill="black", font=font)

    qr_images.append(labeled_img)

# Dimensions of one labeled QR
w, h = qr_images[0].size
rows = (num_codes + cols - 1) // cols
grid_w = cols * w
grid_h = rows * h

# Create final grid
# final_img = Image.new("RGB", (grid_w, grid_h), "white")
final_img = Image.new("RGBA", (grid_w, grid_h), (0, 0, 0, 0))

for idx, qr_img in enumerate(qr_images):
    row, col = divmod(idx, cols)
    final_img.paste(qr_img, (col * w, row * h))

final_img.save("all_qrcodes_labeled.png")
final_img.show()
